### ISSUE TITLE
v2.0 TODO

### ISSUE THREAD

**Issue by Seyeght** [p455w0rd/p455w0rd-s-Things#12]
Dank Null Dock:
When inputting items from the Dank Null Dock it doesnt work in Selected item only mode, and when pulling from All Items mode it only pulls the first item in the Dank Null and seems to delete all other items in the Dank Null.
EnderIO only able to pull items from All Items mode
AE2 only able to pull items from All Items Mode
Extra Utilities Transfer nodes doesnt pull items from either mode.
Vanilla only pulls items from All Items Mode.

Shift Double-Click removes 2 stacks from inventory (not all stacks) and only inserts one stack into the Dank Null.

Interchangers:
I still need to build a massive system to test true max RF/t transfer, but it should be at least 2.14 Billion RF/T, which lets face it, should be MORE than enough. (Tested at 65MeRF/t so.. yeah no issues so far)
Once placed, and any modification made to them they will no longer stack with other Interchangers, even if configuration is exactly the same. 
Eventually would be nice to click a dye onto the outside to immediately set a specific color to one of the spots.
Add right click functionality to all aspects of the GUI to go backwards a step instead of forward, right now the color code has right and left click go forward, and the rest of the GUI ignores right click.

Misc:
Carbon horse armor needs a Smeltery recipe, all horse armors need a crafting recipe.
Will carbon armor need a Smeltery recipe to melt back down to carbon? (not sure why anyone would actually want to do this) 
Will Carbon Bricks/Stairs have a Smeltery recipe?

**Comment by p455w0rd** [comment]
Going to make a checklist here (possibly with additional stuff):
- [X] Fix /dank/null dock tile
- [X] Fix /dank/null shift+double-click in GUI
- [X] Add right-click to reverse-cycle channel colors (other right-clicks not rly necessary)
- [X] Horse armor Smeltery recipes
- [X] Horse Armor Recipes (with config)
- [X] Add carbon slabs
- [X] Add using BBW to pull from /dank/null (pending contact with @portablejim )
- [X] Ditch Tesla in favor of forge energy
- [X] Add Forge Energy support to all RF Items/Tiles
- [X] Add IItemHandler compat to anything applicable
- [X] Fix model lighting in SMP on certain blocks
- [X] Fix lag/fps hit caused by compressor
- [X] Some sort of guide
- [X] hide TiC horse armors if tic not present
- [X] Fix Carbon stairs harvestability
- [X] Fix crash when crouch+right-click with /dank/null in off hand
- [X] Fix /dank/null not picking up items when pickaxe in main hand
- [X] Fix crash when pressing nightvision key when goggles aren't equipped

going to leave the bricks/stairs smeltery recipes alone for now..might implement in the future
